//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Business.wsS29 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="uciMethodsSoap", Namespace="http://tempuri.org/")]
    public partial class uciMethods : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ProcessingTransactionISO_WEBOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public uciMethods() {
            this.Url = global::Business.Properties.Settings.Default.Business_wsS29_uciMethods;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ProcessingTransactionISO_WEBCompletedEventHandler ProcessingTransactionISO_WEBCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ProcessingTransactionISO_WEB", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Iso8583 ProcessingTransactionISO_WEB(Iso8583 iso) {
            object[] results = this.Invoke("ProcessingTransactionISO_WEB", new object[] {
                        iso});
            return ((Iso8583)(results[0]));
        }
        
        /// <remarks/>
        public void ProcessingTransactionISO_WEBAsync(Iso8583 iso) {
            this.ProcessingTransactionISO_WEBAsync(iso, null);
        }
        
        /// <remarks/>
        public void ProcessingTransactionISO_WEBAsync(Iso8583 iso, object userState) {
            if ((this.ProcessingTransactionISO_WEBOperationCompleted == null)) {
                this.ProcessingTransactionISO_WEBOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProcessingTransactionISO_WEBOperationCompleted);
            }
            this.InvokeAsync("ProcessingTransactionISO_WEB", new object[] {
                        iso}, this.ProcessingTransactionISO_WEBOperationCompleted, userState);
        }
        
        private void OnProcessingTransactionISO_WEBOperationCompleted(object arg) {
            if ((this.ProcessingTransactionISO_WEBCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProcessingTransactionISO_WEBCompleted(this, new ProcessingTransactionISO_WEBCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Iso8583 {
        
        private string iSO_000_Message_TypeField;
        
        private string iSO_BITMAPField;
        
        private string iSO_002_PANField;
        
        private string iSO_003_ProcessingCodeField;
        
        private decimal iSO_004_AmountTransactionField;
        
        private decimal iSO_006_BillAmountField;
        
        private decimal iSO_008_BillFeeAmountField;
        
        private System.DateTime iSO_007_TransDatetimeField;
        
        private string iSO_011_SysAuditNumberField;
        
        private System.DateTime iSO_012_LocalDatetimeField;
        
        private System.DateTime iSO_013_LocalDateField;
        
        private System.DateTime iSO_015_SettlementDatelField;
        
        private string iSO_018_MerchantTypeField;
        
        private string iSO_019_AcqCountryCodeField;
        
        private string iSO_022_PosEntryModeField;
        
        private string iSO_023_CardSeqField;
        
        private string iSO_024_NetworkIdField;
        
        private decimal iSO_028_TranFeeAmountField;
        
        private decimal iSO_029_SettlementFeeField;
        
        private decimal iSO_030_ProcFeeField;
        
        private string iSO_032_ACQInsIDField;
        
        private string iSO_033_FWDInsIDField;
        
        private string iSO_034_PANExtField;
        
        private string iSO_035_Track2Field;
        
        private string iSO_036_Track3Field;
        
        private string iSO_037_RetrievalReferenceNumberField;
        
        private string iSO_038_AutorizationNumberField;
        
        private string iSO_039_ResponseCodeField;
        
        private string iSO_039p_ResponseDetailField;
        
        private string iSO_041_CardAcceptorIDField;
        
        private string iSO_042_Card_Acc_ID_CodeField;
        
        private string iSO_043_CardAcceptorLocField;
        
        private string iSO_044_AddRespDataField;
        
        private decimal iSO_049_TranCurrCodeField;
        
        private decimal iSO_051_CardCurrCodeField;
        
        private string iSO_052_PinBlockField;
        
        private string iSO_054_AditionalAmountsField;
        
        private string iSO_055_EMVField;
        
        private string iSO_090_OriginalDataField;
        
        private string iSO_102_AccountID_1Field;
        
        private string iSO_103_AccountID_2Field;
        
        private string iSO_104_TranDescriptionField;
        
        private string iSO_114_ExtendedDataField;
        
        private string iSO_115_ExtendedDataField;
        
        private string iSO_120_ExtendedDataField;
        
        private string iSO_121_ExtendedDataField;
        
        private string iSO_122_ExtendedDataField;
        
        private string iSO_123_ExtendedDataField;
        
        private string iSO_124_ExtendedDataField;
        
        /// <comentarios/>
        public string ISO_000_Message_Type {
            get {
                return this.iSO_000_Message_TypeField;
            }
            set {
                this.iSO_000_Message_TypeField = value;
            }
        }
        
        /// <comentarios/>
        public string ISO_BITMAP {
            get {
                return this.iSO_BITMAPField;
            }
            set {
                this.iSO_BITMAPField = value;
            }
        }
        
        /// <comentarios/>
        public string ISO_002_PAN {
            get {
                return this.iSO_002_PANField;
            }
            set {
                this.iSO_002_PANField = value;
            }
        }
        
        /// <comentarios/>
        public string ISO_003_ProcessingCode {
            get {
                return this.iSO_003_ProcessingCodeField;
            }
            set {
                this.iSO_003_ProcessingCodeField = value;
            }
        }
        
        /// <comentarios/>
        public decimal ISO_004_AmountTransaction {
            get {
                return this.iSO_004_AmountTransactionField;
            }
            set {
                this.iSO_004_AmountTransactionField = value;
            }
        }
        
        /// <comentarios/>
        public decimal ISO_006_BillAmount {
            get {
                return this.iSO_006_BillAmountField;
            }
            set {
                this.iSO_006_BillAmountField = value;
            }
        }
        
        /// <comentarios/>
        public decimal ISO_008_BillFeeAmount {
            get {
                return this.iSO_008_BillFeeAmountField;
            }
            set {
                this.iSO_008_BillFeeAmountField = value;
            }
        }
        
        /// <comentarios/>
        public System.DateTime ISO_007_TransDatetime {
            get {
                return this.iSO_007_TransDatetimeField;
            }
            set {
                this.iSO_007_TransDatetimeField = value;
            }
        }
        
        /// <comentarios/>
        public string ISO_011_SysAuditNumber {
            get {
                return this.iSO_011_SysAuditNumberField;
            }
            set {
                this.iSO_011_SysAuditNumberField = value;
            }
        }
        
        /// <comentarios/>
        public System.DateTime ISO_012_LocalDatetime {
            get {
                return this.iSO_012_LocalDatetimeField;
            }
            set {
                this.iSO_012_LocalDatetimeField = value;
            }
        }
        
        /// <comentarios/>
        public System.DateTime ISO_013_LocalDate {
            get {
                return this.iSO_013_LocalDateField;
            }
            set {
                this.iSO_013_LocalDateField = value;
            }
        }
        
        /// <comentarios/>
        public System.DateTime ISO_015_SettlementDatel {
            get {
                return this.iSO_015_SettlementDatelField;
            }
            set {
                this.iSO_015_SettlementDatelField = value;
            }
        }
        
        /// <comentarios/>
        public string ISO_018_MerchantType {
            get {
                return this.iSO_018_MerchantTypeField;
            }
            set {
                this.iSO_018_MerchantTypeField = value;
            }
        }
        
        /// <comentarios/>
        public string ISO_019_AcqCountryCode {
            get {
                return this.iSO_019_AcqCountryCodeField;
            }
            set {
                this.iSO_019_AcqCountryCodeField = value;
            }
        }
        
        /// <comentarios/>
        public string ISO_022_PosEntryMode {
            get {
                return this.iSO_022_PosEntryModeField;
            }
            set {
                this.iSO_022_PosEntryModeField = value;
            }
        }
        
        /// <comentarios/>
        public string ISO_023_CardSeq {
            get {
                return this.iSO_023_CardSeqField;
            }
            set {
                this.iSO_023_CardSeqField = value;
            }
        }
        
        /// <comentarios/>
        public string ISO_024_NetworkId {
            get {
                return this.iSO_024_NetworkIdField;
            }
            set {
                this.iSO_024_NetworkIdField = value;
            }
        }
        
        /// <comentarios/>
        public decimal ISO_028_TranFeeAmount {
            get {
                return this.iSO_028_TranFeeAmountField;
            }
            set {
                this.iSO_028_TranFeeAmountField = value;
            }
        }
        
        /// <comentarios/>
        public decimal ISO_029_SettlementFee {
            get {
                return this.iSO_029_SettlementFeeField;
            }
            set {
                this.iSO_029_SettlementFeeField = value;
            }
        }
        
        /// <comentarios/>
        public decimal ISO_030_ProcFee {
            get {
                return this.iSO_030_ProcFeeField;
            }
            set {
                this.iSO_030_ProcFeeField = value;
            }
        }
        
        /// <comentarios/>
        public string ISO_032_ACQInsID {
            get {
                return this.iSO_032_ACQInsIDField;
            }
            set {
                this.iSO_032_ACQInsIDField = value;
            }
        }
        
        /// <comentarios/>
        public string ISO_033_FWDInsID {
            get {
                return this.iSO_033_FWDInsIDField;
            }
            set {
                this.iSO_033_FWDInsIDField = value;
            }
        }
        
        /// <comentarios/>
        public string ISO_034_PANExt {
            get {
                return this.iSO_034_PANExtField;
            }
            set {
                this.iSO_034_PANExtField = value;
            }
        }
        
        /// <comentarios/>
        public string ISO_035_Track2 {
            get {
                return this.iSO_035_Track2Field;
            }
            set {
                this.iSO_035_Track2Field = value;
            }
        }
        
        /// <comentarios/>
        public string ISO_036_Track3 {
            get {
                return this.iSO_036_Track3Field;
            }
            set {
                this.iSO_036_Track3Field = value;
            }
        }
        
        /// <comentarios/>
        public string ISO_037_RetrievalReferenceNumber {
            get {
                return this.iSO_037_RetrievalReferenceNumberField;
            }
            set {
                this.iSO_037_RetrievalReferenceNumberField = value;
            }
        }
        
        /// <comentarios/>
        public string ISO_038_AutorizationNumber {
            get {
                return this.iSO_038_AutorizationNumberField;
            }
            set {
                this.iSO_038_AutorizationNumberField = value;
            }
        }
        
        /// <comentarios/>
        public string ISO_039_ResponseCode {
            get {
                return this.iSO_039_ResponseCodeField;
            }
            set {
                this.iSO_039_ResponseCodeField = value;
            }
        }
        
        /// <comentarios/>
        public string ISO_039p_ResponseDetail {
            get {
                return this.iSO_039p_ResponseDetailField;
            }
            set {
                this.iSO_039p_ResponseDetailField = value;
            }
        }
        
        /// <comentarios/>
        public string ISO_041_CardAcceptorID {
            get {
                return this.iSO_041_CardAcceptorIDField;
            }
            set {
                this.iSO_041_CardAcceptorIDField = value;
            }
        }
        
        /// <comentarios/>
        public string ISO_042_Card_Acc_ID_Code {
            get {
                return this.iSO_042_Card_Acc_ID_CodeField;
            }
            set {
                this.iSO_042_Card_Acc_ID_CodeField = value;
            }
        }
        
        /// <comentarios/>
        public string ISO_043_CardAcceptorLoc {
            get {
                return this.iSO_043_CardAcceptorLocField;
            }
            set {
                this.iSO_043_CardAcceptorLocField = value;
            }
        }
        
        /// <comentarios/>
        public string ISO_044_AddRespData {
            get {
                return this.iSO_044_AddRespDataField;
            }
            set {
                this.iSO_044_AddRespDataField = value;
            }
        }
        
        /// <comentarios/>
        public decimal ISO_049_TranCurrCode {
            get {
                return this.iSO_049_TranCurrCodeField;
            }
            set {
                this.iSO_049_TranCurrCodeField = value;
            }
        }
        
        /// <comentarios/>
        public decimal ISO_051_CardCurrCode {
            get {
                return this.iSO_051_CardCurrCodeField;
            }
            set {
                this.iSO_051_CardCurrCodeField = value;
            }
        }
        
        /// <comentarios/>
        public string ISO_052_PinBlock {
            get {
                return this.iSO_052_PinBlockField;
            }
            set {
                this.iSO_052_PinBlockField = value;
            }
        }
        
        /// <comentarios/>
        public string ISO_054_AditionalAmounts {
            get {
                return this.iSO_054_AditionalAmountsField;
            }
            set {
                this.iSO_054_AditionalAmountsField = value;
            }
        }
        
        /// <comentarios/>
        public string ISO_055_EMV {
            get {
                return this.iSO_055_EMVField;
            }
            set {
                this.iSO_055_EMVField = value;
            }
        }
        
        /// <comentarios/>
        public string ISO_090_OriginalData {
            get {
                return this.iSO_090_OriginalDataField;
            }
            set {
                this.iSO_090_OriginalDataField = value;
            }
        }
        
        /// <comentarios/>
        public string ISO_102_AccountID_1 {
            get {
                return this.iSO_102_AccountID_1Field;
            }
            set {
                this.iSO_102_AccountID_1Field = value;
            }
        }
        
        /// <comentarios/>
        public string ISO_103_AccountID_2 {
            get {
                return this.iSO_103_AccountID_2Field;
            }
            set {
                this.iSO_103_AccountID_2Field = value;
            }
        }
        
        /// <comentarios/>
        public string ISO_104_TranDescription {
            get {
                return this.iSO_104_TranDescriptionField;
            }
            set {
                this.iSO_104_TranDescriptionField = value;
            }
        }
        
        /// <comentarios/>
        public string ISO_114_ExtendedData {
            get {
                return this.iSO_114_ExtendedDataField;
            }
            set {
                this.iSO_114_ExtendedDataField = value;
            }
        }
        
        /// <comentarios/>
        public string ISO_115_ExtendedData {
            get {
                return this.iSO_115_ExtendedDataField;
            }
            set {
                this.iSO_115_ExtendedDataField = value;
            }
        }
        
        /// <comentarios/>
        public string ISO_120_ExtendedData {
            get {
                return this.iSO_120_ExtendedDataField;
            }
            set {
                this.iSO_120_ExtendedDataField = value;
            }
        }
        
        /// <comentarios/>
        public string ISO_121_ExtendedData {
            get {
                return this.iSO_121_ExtendedDataField;
            }
            set {
                this.iSO_121_ExtendedDataField = value;
            }
        }
        
        /// <comentarios/>
        public string ISO_122_ExtendedData {
            get {
                return this.iSO_122_ExtendedDataField;
            }
            set {
                this.iSO_122_ExtendedDataField = value;
            }
        }
        
        /// <comentarios/>
        public string ISO_123_ExtendedData {
            get {
                return this.iSO_123_ExtendedDataField;
            }
            set {
                this.iSO_123_ExtendedDataField = value;
            }
        }
        
        /// <comentarios/>
        public string ISO_124_ExtendedData {
            get {
                return this.iSO_124_ExtendedDataField;
            }
            set {
                this.iSO_124_ExtendedDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void ProcessingTransactionISO_WEBCompletedEventHandler(object sender, ProcessingTransactionISO_WEBCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProcessingTransactionISO_WEBCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ProcessingTransactionISO_WEBCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Iso8583 Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Iso8583)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591