//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Business.wsCompers {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebService29OctubreSoap", Namespace="http://tempuri.org/")]
    public partial class WebService29Octubre : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private LoginInfo loginInfoValueField;
        
        private System.Threading.SendOrPostCallback InsertaOActualizaAreaOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertaOActualizaCargoOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertaOActualizaPersonaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebService29Octubre() {
            this.Url = global::Business.Properties.Settings.Default.Business_wsCompers_WebService29Octubre;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public LoginInfo LoginInfoValue {
            get {
                return this.loginInfoValueField;
            }
            set {
                this.loginInfoValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event InsertaOActualizaAreaCompletedEventHandler InsertaOActualizaAreaCompleted;
        
        /// <remarks/>
        public event InsertaOActualizaCargoCompletedEventHandler InsertaOActualizaCargoCompleted;
        
        /// <remarks/>
        public event InsertaOActualizaPersonaCompletedEventHandler InsertaOActualizaPersonaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("LoginInfoValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertaOActualizaArea", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool InsertaOActualizaArea(int AreaSec, int AreaSecPadre, string AreaNombre, int AreaNivel, string AreaEstado) {
            object[] results = this.Invoke("InsertaOActualizaArea", new object[] {
                        AreaSec,
                        AreaSecPadre,
                        AreaNombre,
                        AreaNivel,
                        AreaEstado});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void InsertaOActualizaAreaAsync(int AreaSec, int AreaSecPadre, string AreaNombre, int AreaNivel, string AreaEstado) {
            this.InsertaOActualizaAreaAsync(AreaSec, AreaSecPadre, AreaNombre, AreaNivel, AreaEstado, null);
        }
        
        /// <remarks/>
        public void InsertaOActualizaAreaAsync(int AreaSec, int AreaSecPadre, string AreaNombre, int AreaNivel, string AreaEstado, object userState) {
            if ((this.InsertaOActualizaAreaOperationCompleted == null)) {
                this.InsertaOActualizaAreaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertaOActualizaAreaOperationCompleted);
            }
            this.InvokeAsync("InsertaOActualizaArea", new object[] {
                        AreaSec,
                        AreaSecPadre,
                        AreaNombre,
                        AreaNivel,
                        AreaEstado}, this.InsertaOActualizaAreaOperationCompleted, userState);
        }
        
        private void OnInsertaOActualizaAreaOperationCompleted(object arg) {
            if ((this.InsertaOActualizaAreaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertaOActualizaAreaCompleted(this, new InsertaOActualizaAreaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("LoginInfoValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertaOActualizaCargo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool InsertaOActualizaCargo(int CargoSec, string CargoNombre, string CargoEstado) {
            object[] results = this.Invoke("InsertaOActualizaCargo", new object[] {
                        CargoSec,
                        CargoNombre,
                        CargoEstado});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void InsertaOActualizaCargoAsync(int CargoSec, string CargoNombre, string CargoEstado) {
            this.InsertaOActualizaCargoAsync(CargoSec, CargoNombre, CargoEstado, null);
        }
        
        /// <remarks/>
        public void InsertaOActualizaCargoAsync(int CargoSec, string CargoNombre, string CargoEstado, object userState) {
            if ((this.InsertaOActualizaCargoOperationCompleted == null)) {
                this.InsertaOActualizaCargoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertaOActualizaCargoOperationCompleted);
            }
            this.InvokeAsync("InsertaOActualizaCargo", new object[] {
                        CargoSec,
                        CargoNombre,
                        CargoEstado}, this.InsertaOActualizaCargoOperationCompleted, userState);
        }
        
        private void OnInsertaOActualizaCargoOperationCompleted(object arg) {
            if ((this.InsertaOActualizaCargoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertaOActualizaCargoCompleted(this, new InsertaOActualizaCargoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("LoginInfoValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertaOActualizaPersona", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool InsertaOActualizaPersona(
                    int PersonaSec, 
                    int AreaSec, 
                    int CargoSec, 
                    string PersonaNombre, 
                    string PersonaApellido, 
                    double PersonaSueldo, 
                    string PersonaCI, 
                    int PersonaSupervisor, 
                    string PersonaFechaNacimiento, 
                    string PersonaFechaIngreso, 
                    int PersonaGenero, 
                    string PersonaDireccion, 
                    string PersonaTelefonoDomicilio, 
                    string PersonaTelefonoMovil, 
                    string PersonaTelefonoLaboral, 
                    string PersonaTelefonoExtension, 
                    string PersonaCodigo, 
                    string PersonaCorreo, 
                    string PersonaEstado) {
            object[] results = this.Invoke("InsertaOActualizaPersona", new object[] {
                        PersonaSec,
                        AreaSec,
                        CargoSec,
                        PersonaNombre,
                        PersonaApellido,
                        PersonaSueldo,
                        PersonaCI,
                        PersonaSupervisor,
                        PersonaFechaNacimiento,
                        PersonaFechaIngreso,
                        PersonaGenero,
                        PersonaDireccion,
                        PersonaTelefonoDomicilio,
                        PersonaTelefonoMovil,
                        PersonaTelefonoLaboral,
                        PersonaTelefonoExtension,
                        PersonaCodigo,
                        PersonaCorreo,
                        PersonaEstado});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void InsertaOActualizaPersonaAsync(
                    int PersonaSec, 
                    int AreaSec, 
                    int CargoSec, 
                    string PersonaNombre, 
                    string PersonaApellido, 
                    double PersonaSueldo, 
                    string PersonaCI, 
                    int PersonaSupervisor, 
                    string PersonaFechaNacimiento, 
                    string PersonaFechaIngreso, 
                    int PersonaGenero, 
                    string PersonaDireccion, 
                    string PersonaTelefonoDomicilio, 
                    string PersonaTelefonoMovil, 
                    string PersonaTelefonoLaboral, 
                    string PersonaTelefonoExtension, 
                    string PersonaCodigo, 
                    string PersonaCorreo, 
                    string PersonaEstado) {
            this.InsertaOActualizaPersonaAsync(PersonaSec, AreaSec, CargoSec, PersonaNombre, PersonaApellido, PersonaSueldo, PersonaCI, PersonaSupervisor, PersonaFechaNacimiento, PersonaFechaIngreso, PersonaGenero, PersonaDireccion, PersonaTelefonoDomicilio, PersonaTelefonoMovil, PersonaTelefonoLaboral, PersonaTelefonoExtension, PersonaCodigo, PersonaCorreo, PersonaEstado, null);
        }
        
        /// <remarks/>
        public void InsertaOActualizaPersonaAsync(
                    int PersonaSec, 
                    int AreaSec, 
                    int CargoSec, 
                    string PersonaNombre, 
                    string PersonaApellido, 
                    double PersonaSueldo, 
                    string PersonaCI, 
                    int PersonaSupervisor, 
                    string PersonaFechaNacimiento, 
                    string PersonaFechaIngreso, 
                    int PersonaGenero, 
                    string PersonaDireccion, 
                    string PersonaTelefonoDomicilio, 
                    string PersonaTelefonoMovil, 
                    string PersonaTelefonoLaboral, 
                    string PersonaTelefonoExtension, 
                    string PersonaCodigo, 
                    string PersonaCorreo, 
                    string PersonaEstado, 
                    object userState) {
            if ((this.InsertaOActualizaPersonaOperationCompleted == null)) {
                this.InsertaOActualizaPersonaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertaOActualizaPersonaOperationCompleted);
            }
            this.InvokeAsync("InsertaOActualizaPersona", new object[] {
                        PersonaSec,
                        AreaSec,
                        CargoSec,
                        PersonaNombre,
                        PersonaApellido,
                        PersonaSueldo,
                        PersonaCI,
                        PersonaSupervisor,
                        PersonaFechaNacimiento,
                        PersonaFechaIngreso,
                        PersonaGenero,
                        PersonaDireccion,
                        PersonaTelefonoDomicilio,
                        PersonaTelefonoMovil,
                        PersonaTelefonoLaboral,
                        PersonaTelefonoExtension,
                        PersonaCodigo,
                        PersonaCorreo,
                        PersonaEstado}, this.InsertaOActualizaPersonaOperationCompleted, userState);
        }
        
        private void OnInsertaOActualizaPersonaOperationCompleted(object arg) {
            if ((this.InsertaOActualizaPersonaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertaOActualizaPersonaCompleted(this, new InsertaOActualizaPersonaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/", IsNullable=false)]
    public partial class LoginInfo : System.Web.Services.Protocols.SoapHeader {
        
        private string userNameField;
        
        private string passWordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <comentarios/>
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <comentarios/>
        public string PassWord {
            get {
                return this.passWordField;
            }
            set {
                this.passWordField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void InsertaOActualizaAreaCompletedEventHandler(object sender, InsertaOActualizaAreaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertaOActualizaAreaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertaOActualizaAreaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void InsertaOActualizaCargoCompletedEventHandler(object sender, InsertaOActualizaCargoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertaOActualizaCargoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertaOActualizaCargoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void InsertaOActualizaPersonaCompletedEventHandler(object sender, InsertaOActualizaPersonaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertaOActualizaPersonaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertaOActualizaPersonaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591